### ISSUE TITLE
fsatrace isn't recording executable being run as a "read".

### ISSUE THREAD

**Issue by spall** [ndmitchell/rattle#1]
Fsatrace doesn't appear to record the running executable as being read.  I am specifically seeing this as an issue for the current test case, Test.hs; with fstrace recording "./Main" as having no reads or writes.

**Comment by ndmitchell** [comment]
Can you please raise this issue upstream with https://github.com/jacereda/fsatrace as well, and cc me? I note I fixed an issue a lot like this on windows recently in fsatrace.

**Comment by spall** [comment]
Yes.

**Comment by spall** [comment]
This now seems to be fixed for Linux in fsatrace.

**Comment by ndmitchell** [comment]
Awesome!
